# Generated by Django 4.2.5 on 2023-09-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BonDeCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_commande", models.DateField()),
                ("produits", models.TextField()),
                ("quantites", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.TextField()),
                ("telephone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_facture", models.DateField()),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numero_facture", models.CharField(max_length=50)),
                ("statut", models.CharField(max_length=20)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vente.bondecommande",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_devis", models.DateField()),
                ("produits", models.TextField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vente.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BonDeRetour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_retour", models.DateField()),
                ("produits_retournes", models.TextField()),
                ("quantites_retournees", models.TextField()),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vente.bondecommande",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BonDeLivraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_livraison", models.DateField()),
                ("produits_livres", models.TextField()),
                ("quantites_livrees", models.TextField()),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vente.bondecommande",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bondecommande",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vente.client"
            ),
        ),
        migrations.CreateModel(
            name="AvoirClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_avoir", models.DateField()),
                ("montant_avoir", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numero_avoir", models.CharField(max_length=50)),
                ("motif", models.TextField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vente.client"
                    ),
                ),
            ],
        ),
    ]
