# Generated by Django 4.2.5 on 2023-10-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vente", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="adresse",
            new_name="ville",
        ),
        migrations.AddField(
            model_name="client",
            name="soldefacture",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="client",
            name="soldeglobal",
            field=models.FloatField(default=0.0),
        ),
    ]
