# Generated by Django 4.2.5 on 2023-11-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vente", "0002_rename_adresse_client_ville_client_soldefacture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.IntegerField(max_length=8),
        ),
    ]
